### ISSUE TITLE
Support Splunk version 6.5

### ISSUE THREAD

**Issue by tmortiboy** [httpstergeek/d3-splunk-extentions#2]
Would it be possible to add compatibility with splunk 6.5?

**Comment by httpstergeek** [comment]
Technically it is compatible with 6.5. It just doesn't use the Custom Visualization

**Comment by tmortiboy** [comment]
Does that mean it would be possible to install into splunk cloud?

**Comment by httpstergeek** [comment]
Yes,  if you talk to Splunk Cloud support.  Sorry been on vacation.
